// Top Business Countries & Global Supply Chain Hub Locations
export const TOP_BUSINESS_COUNTRIES = [
  { country: "China",          latitude: 35.8617, longitude: 104.1954,
    hub: { city: "Shanghai",   latitude: 31.2304, longitude: 121.4737 } },
  { country: "United States",  latitude: 37.0902, longitude: -95.7129,
    hub: { city: "New York",   latitude: 40.7128, longitude: -74.006 } },
  { country: "Germany",        latitude: 51.1657, longitude: 10.4515,
    hub: { city: "Frankfurt",  latitude: 50.1109, longitude: 8.6821 } },
  { country: "Japan",          latitude: 36.2048, longitude: 138.2529,
    hub: { city: "Tokyo",      latitude: 35.6762, longitude: 139.6503 } },
  { country: "India",          latitude: 20.5937, longitude: 78.9629,
    hub: { city: "Mumbai",     latitude: 19.076,  longitude: 72.8777 } },
  { country: "United Kingdom", latitude: 55.3781, longitude: -3.436,
    hub: { city: "London",     latitude: 51.5074, longitude: -0.1278 } },
  { country: "France",         latitude: 46.2276, longitude: 2.2137,
    hub: { city: "Paris",      latitude: 48.8566, longitude: 2.3522 } },
  { country: "South Korea",    latitude: 35.9078, longitude: 127.7669,
    hub: { city: "Seoul",      latitude: 37.5665, longitude: 126.978 } },
  { country: "Netherlands",    latitude: 52.1326, longitude: 5.2913,
    hub: { city: "Rotterdam",  latitude: 51.9244, longitude: 4.4777 } },
  { country: "Singapore",      latitude: 1.3521,  longitude: 103.8198,
    hub: { city: "Singapore",  latitude: 1.3521,  longitude: 103.8198 } },
];

// Comprehensive Tracking Data: Countries -> Top City Hubs -> Suppliers & Vendors
export const INITIAL_TRACKING_DATA = [
  {
    country: "China",
    state: "China",
    latitude: 35.8617,
    longitude: 104.1954,
    hub: {
      city: "Shanghai",
      latitude: 31.2304,
      longitude: 121.4737,
    },
    cities: [
      {
        city: "Shanghai",
        latitude: 31.2304,
        longitude: 121.4737,
        suppliers: [
          {
            id: "SUP-SHA-001",
            name: "Shanghai Orient Toner Co.",
            latitude: 31.2304,
            longitude: 121.4737,
            location: "Pudong New Area, Shanghai",
          },
          {
            id: "SUP-SHA-002",
            name: "East China Print Consumables",
            latitude: 31.2304,
            longitude: 121.4737,
            location: "Huangpu District, Shanghai",
          },
          {
            id: "SUP-SHA-003",
            name: "Yangtze Laser Cartridge Hub",
            latitude: 31.2304,
            longitude: 121.4737,
            location: "Jing'an District, Shanghai",
          },
          {
            id: "SUP-SHA-004",
            name: "Shanghai Precision Imaging Ltd",
            latitude: 31.2304,
            longitude: 121.4737,
            location: "Xuhui District, Shanghai",
          },
          {
            id: "SUP-SHA-005",
            name: "Great Wall Toner & Ink",
            latitude: 31.2304,
            longitude: 121.4737,
            location: "Minhang District, Shanghai",
          },
          {
            id: "SUP-SHA-006",
            name: "Golden Dragon Office Solutions",
            latitude: 31.2304,
            longitude: 121.4737,
            location: "Hongqiao Hub, Shanghai",
          },
          {
            id: "SUP-SHA-007",
            name: "Sinoprint Tech Distribution",
            latitude: 31.2304,
            longitude: 121.4737,
            location: "Baoshan District, Shanghai",
          },
          {
            id: "SUP-SHA-008",
            name: "Apex Color Toner Manufacturing",
            latitude: 31.2304,
            longitude: 121.4737,
            location: "Songjiang District, Shanghai",
          },
          {
            id: "SUP-SHA-009",
            name: "Shanghai Cartridge Logistics",
            latitude: 31.2304,
            longitude: 121.4737,
            location: "Jiading District, Shanghai",
          },
          {
            id: "SUP-SHA-010",
            name: "Huashan Print Supply Co.",
            latitude: 31.2304,
            longitude: 121.4737,
            location: "Yangpu District, Shanghai",
          },
        ],
        vendors: [
          {
            id: "VEN-SHA-001",
            name: "Shanghai Digital Imaging Store",
            latitude: 31.2304,
            longitude: 121.4737,
            location: "People's Square, Shanghai",
          },
          {
            id: "VEN-SHA-002",
            name: "Lujiazui Financial Print Hub",
            latitude: 31.2304,
            longitude: 121.4737,
            location: "Pudong, Shanghai",
          },
          {
            id: "VEN-SHA-003",
            name: "Century Tech Office Mart",
            latitude: 31.2304,
            longitude: 121.4737,
            location: "Hongkou, Shanghai",
          },
          {
            id: "VEN-SHA-004",
            name: "Silk Road Toner Retail",
            latitude: 31.2304,
            longitude: 121.4737,
            location: "Putuo District, Shanghai",
          },
          {
            id: "VEN-SHA-005",
            name: "MetroPrint Express Hub",
            latitude: 31.2304,
            longitude: 121.4737,
            location: "Changning District, Shanghai",
          },
          {
            id: "VEN-SHA-006",
            name: "Pacific Ink & Toner Solutions",
            latitude: 31.2304,
            longitude: 121.4737,
            location: "Fengxian District, Shanghai",
          },
          {
            id: "VEN-SHA-007",
            name: "Dragon Laser Services",
            latitude: 31.2304,
            longitude: 121.4737,
            location: "Jinshan District, Shanghai",
          },
          {
            id: "VEN-SHA-008",
            name: "Evergreen Office Consumables",
            latitude: 31.2304,
            longitude: 121.4737,
            location: "Qingpu District, Shanghai",
          },
          {
            id: "VEN-SHA-009",
            name: "Zhongshan Print Mart",
            latitude: 31.2304,
            longitude: 121.4737,
            location: "Zhabei District, Shanghai",
          },
          {
            id: "VEN-SHA-010",
            name: "East Sea Cartridge Solutions",
            latitude: 31.2304,
            longitude: 121.4737,
            location: "Chongming, Shanghai",
          },
        ],
      },
    ],
  },
  {
    country: "United States",
    state: "United States",
    latitude: 37.0902,
    longitude: -95.7129,
    hub: {
      city: "New York",
      latitude: 40.7128,
      longitude: -74.006,
    },
    cities: [
      {
        city: "New York",
        latitude: 40.7128,
        longitude: -74.006,
        suppliers: [
          {
            id: "SUP-NYC-001",
            name: "Manhattan Office Supplies & Toner",
            latitude: 40.7128,
            longitude: -74.006,
            location: "Midtown Manhattan, New York",
          },
          {
            id: "SUP-NYC-002",
            name: "Empire State Cartridge Corp",
            latitude: 40.7128,
            longitude: -74.006,
            location: "Financial District, New York",
          },
          {
            id: "SUP-NYC-003",
            name: "Hudson Valley Laser Print Co.",
            latitude: 40.7128,
            longitude: -74.006,
            location: "Chelsea, New York",
          },
          {
            id: "SUP-NYC-004",
            name: "Brooklyn Supply Logistics",
            latitude: 40.7128,
            longitude: -74.006,
            location: "Downtown Brooklyn, New York",
          },
          {
            id: "SUP-NYC-005",
            name: "Metropolitan Toner Distributors",
            latitude: 40.7128,
            longitude: -74.006,
            location: "Long Island City, New York",
          },
          {
            id: "SUP-NYC-006",
            name: "Liberty Print Consumables",
            latitude: 40.7128,
            longitude: -74.006,
            location: "SoHo, New York",
          },
          {
            id: "SUP-NYC-007",
            name: "Broadway Office Solutions",
            latitude: 40.7128,
            longitude: -74.006,
            location: "Times Square, New York",
          },
          {
            id: "SUP-NYC-008",
            name: "Queens Cartridge & Toner Center",
            latitude: 40.7128,
            longitude: -74.006,
            location: "Astoria, Queens, New York",
          },
          {
            id: "SUP-NYC-009",
            name: "Gotham Imaging & Ink Depot",
            latitude: 40.7128,
            longitude: -74.006,
            location: "Flatiron District, New York",
          },
          {
            id: "SUP-NYC-010",
            name: "Tri-State Print Technologies",
            latitude: 40.7128,
            longitude: -74.006,
            location: "Upper East Side, New York",
          },
        ],
        vendors: [
          {
            id: "VEN-NYC-001",
            name: "NY Laser Toner Direct",
            latitude: 40.7128,
            longitude: -74.006,
            location: "Grand Central, New York",
          },
          {
            id: "VEN-NYC-002",
            name: "Wall Street Print Mart",
            latitude: 40.7128,
            longitude: -74.006,
            location: "Lower Manhattan, New York",
          },
          {
            id: "VEN-NYC-003",
            name: "Greenwich Village Stationery",
            latitude: 40.7128,
            longitude: -74.006,
            location: "West Village, New York",
          },
          {
            id: "VEN-NYC-004",
            name: "Central Park Office Hub",
            latitude: 40.7128,
            longitude: -74.006,
            location: "Upper West Side, New York",
          },
          {
            id: "VEN-NYC-005",
            name: "Harlem Print & Copy Center",
            latitude: 40.7128,
            longitude: -74.006,
            location: "Harlem, New York",
          },
          {
            id: "VEN-NYC-006",
            name: "Bronx Commercial Supplies",
            latitude: 40.7128,
            longitude: -74.006,
            location: "South Bronx, New York",
          },
          {
            id: "VEN-NYC-007",
            name: "Staten Island Toner Retail",
            latitude: 40.7128,
            longitude: -74.006,
            location: "St. George, New York",
          },
          {
            id: "VEN-NYC-008",
            name: "Madison Avenue Stationery",
            latitude: 40.7128,
            longitude: -74.006,
            location: "Midtown East, New York",
          },
          {
            id: "VEN-NYC-009",
            name: "Hudson Yards Imaging Mart",
            latitude: 40.7128,
            longitude: -74.006,
            location: "Hudson Yards, New York",
          },
          {
            id: "VEN-NYC-010",
            name: "Rockefeller Cartridge Exchange",
            latitude: 40.7128,
            longitude: -74.006,
            location: "Rockefeller Center, New York",
          },
        ],
      },
    ],
  },
  {
    country: "Germany",
    state: "Germany",
    latitude: 51.1657,
    longitude: 10.4515,
    hub: {
      city: "Frankfurt",
      latitude: 50.1109,
      longitude: 8.6821,
    },
    cities: [
      {
        city: "Frankfurt",
        latitude: 50.1109,
        longitude: 8.6821,
        suppliers: [
          {
            id: "SUP-FRA-001",
            name: "Frankfurt Logistikzentrum Toner",
            latitude: 50.1109,
            longitude: 8.6821,
            location: "Innenstadt, Frankfurt",
          },
          {
            id: "SUP-FRA-002",
            name: "Rhein-Main Cartridge GmbH",
            latitude: 50.1109,
            longitude: 8.6821,
            location: "Sachsenhausen, Frankfurt",
          },
          {
            id: "SUP-FRA-003",
            name: "Hessen Druckbedarf & Toner",
            latitude: 50.1109,
            longitude: 8.6821,
            location: "Bockenheim, Frankfurt",
          },
          {
            id: "SUP-FRA-004",
            name: "Deutsche Toner Distribution",
            latitude: 50.1109,
            longitude: 8.6821,
            location: "Westend, Frankfurt",
          },
          {
            id: "SUP-FRA-005",
            name: "Mainhattan Office Supplies",
            latitude: 50.1109,
            longitude: 8.6821,
            location: "Gallus, Frankfurt",
          },
          {
            id: "SUP-FRA-006",
            name: "Taunus Laser & Ink Depot",
            latitude: 50.1109,
            longitude: 8.6821,
            location: "Nordend, Frankfurt",
          },
          {
            id: "SUP-FRA-007",
            name: "EuroPrint Consumables KG",
            latitude: 50.1109,
            longitude: 8.6821,
            location: "Ostend, Frankfurt",
          },
          {
            id: "SUP-FRA-008",
            name: "Bavaria-Hessen Toner Hub",
            latitude: 50.1109,
            longitude: 8.6821,
            location: "Bornheim, Frankfurt",
          },
          {
            id: "SUP-FRA-009",
            name: "Germania Print Technologies",
            latitude: 50.1109,
            longitude: 8.6821,
            location: "Gutleutviertel, Frankfurt",
          },
          {
            id: "SUP-FRA-010",
            name: "Rheinland Cartridge Supply",
            latitude: 50.1109,
            longitude: 8.6821,
            location: "Höchst, Frankfurt",
          },
        ],
        vendors: [
          {
            id: "VEN-FRA-001",
            name: "Frankfurt Bürotechnik Store",
            latitude: 50.1109,
            longitude: 8.6821,
            location: "Zeil, Frankfurt",
          },
          {
            id: "VEN-FRA-002",
            name: "Bankenviertel Print Services",
            latitude: 50.1109,
            longitude: 8.6821,
            location: "Financial District, Frankfurt",
          },
          {
            id: "VEN-FRA-003",
            name: "Airport Cargo Toner Shop",
            latitude: 50.1109,
            longitude: 8.6821,
            location: "Flughafen, Frankfurt",
          },
          {
            id: "VEN-FRA-004",
            name: "Kaiserstraße Stationery Mart",
            latitude: 50.1109,
            longitude: 8.6821,
            location: "Bahnhofsviertel, Frankfurt",
          },
          {
            id: "VEN-FRA-005",
            name: "Goethe Office Solutions",
            latitude: 50.1109,
            longitude: 8.6821,
            location: "Westend-Süd, Frankfurt",
          },
          {
            id: "VEN-FRA-006",
            name: "Sachsenhausen Druck-Shop",
            latitude: 50.1109,
            longitude: 8.6821,
            location: "Schweizer Platz, Frankfurt",
          },
          {
            id: "VEN-FRA-007",
            name: "Main Tower Cartridges",
            latitude: 50.1109,
            longitude: 8.6821,
            location: "Innenstadt-West, Frankfurt",
          },
          {
            id: "VEN-FRA-008",
            name: "Druckerzubehör Express",
            latitude: 50.1109,
            longitude: 8.6821,
            location: "Riederwald, Frankfurt",
          },
          {
            id: "VEN-FRA-009",
            name: "Hessen Toner Outlet",
            latitude: 50.1109,
            longitude: 8.6821,
            location: "Eschersheim, Frankfurt",
          },
          {
            id: "VEN-FRA-010",
            name: "Rhein-Main Bürobedarf",
            latitude: 50.1109,
            longitude: 8.6821,
            location: "Niederrad, Frankfurt",
          },
        ],
      },
    ],
  },
  {
    country: "Japan",
    state: "Japan",
    latitude: 36.2048,
    longitude: 138.2529,
    hub: {
      city: "Tokyo",
      latitude: 35.6762,
      longitude: 139.6503,
    },
    cities: [
      {
        city: "Tokyo",
        latitude: 35.6762,
        longitude: 139.6503,
        suppliers: [
          {
            id: "SUP-TYO-001",
            name: "Tokyo Precision Toner Corp",
            latitude: 35.6762,
            longitude: 139.6503,
            location: "Chiyoda-ku, Tokyo",
          },
          {
            id: "SUP-TYO-002",
            name: "Shinjuku Laser Imaging Co.",
            latitude: 35.6762,
            longitude: 139.6503,
            location: "Shinjuku-ku, Tokyo",
          },
          {
            id: "SUP-TYO-003",
            name: "Kanto Cartridge Logistics",
            latitude: 35.6762,
            longitude: 139.6503,
            location: "Minato-ku, Tokyo",
          },
          {
            id: "SUP-TYO-004",
            name: "Nippon Print Consumables",
            latitude: 35.6762,
            longitude: 139.6503,
            location: "Chuo-ku, Tokyo",
          },
          {
            id: "SUP-TYO-005",
            name: "Akihabara Tech Supply Hub",
            latitude: 35.6762,
            longitude: 139.6503,
            location: "Sotokanda, Tokyo",
          },
          {
            id: "SUP-TYO-006",
            name: "Shibuya Office Innovations",
            latitude: 35.6762,
            longitude: 139.6503,
            location: "Shibuya-ku, Tokyo",
          },
          {
            id: "SUP-TYO-007",
            name: "Ginza Corporate Stationery",
            latitude: 35.6762,
            longitude: 139.6503,
            location: "Ginza, Tokyo",
          },
          {
            id: "SUP-TYO-008",
            name: "Shinagawa Industrial Toner",
            latitude: 35.6762,
            longitude: 139.6503,
            location: "Shinagawa-ku, Tokyo",
          },
          {
            id: "SUP-TYO-009",
            name: "Ikebukuro Print Technologies",
            latitude: 35.6762,
            longitude: 139.6503,
            location: "Toshima-ku, Tokyo",
          },
          {
            id: "SUP-TYO-010",
            name: "Ueno Imaging & Ink Supplies",
            latitude: 35.6762,
            longitude: 139.6503,
            location: "Taito-ku, Tokyo",
          },
        ],
        vendors: [
          {
            id: "VEN-TYO-001",
            name: "Tokyo Business Mart Direct",
            latitude: 35.6762,
            longitude: 139.6503,
            location: "Marunouchi, Tokyo",
          },
          {
            id: "VEN-TYO-002",
            name: "Roppongi Laser Print Solutions",
            latitude: 35.6762,
            longitude: 139.6503,
            location: "Roppongi Hills, Tokyo",
          },
          {
            id: "VEN-TYO-003",
            name: "Akiba Toner & Supplies",
            latitude: 35.6762,
            longitude: 139.6503,
            location: "Akihabara, Tokyo",
          },
          {
            id: "VEN-TYO-004",
            name: "Shinjuku West Office Depot",
            latitude: 35.6762,
            longitude: 139.6503,
            location: "Nishi-Shinjuku, Tokyo",
          },
          {
            id: "VEN-TYO-005",
            name: "Otemachi Corporate Mart",
            latitude: 35.6762,
            longitude: 139.6503,
            location: "Otemachi, Tokyo",
          },
          {
            id: "VEN-TYO-006",
            name: "Nihombashi Stationery Shop",
            latitude: 35.6762,
            longitude: 139.6503,
            location: "Nihombashi, Tokyo",
          },
          {
            id: "VEN-TYO-007",
            name: "Ebisu Imaging Retail",
            latitude: 35.6762,
            longitude: 139.6503,
            location: "Ebisu, Tokyo",
          },
          {
            id: "VEN-TYO-008",
            name: "Asakusa Print Services",
            latitude: 35.6762,
            longitude: 139.6503,
            location: "Asakusa, Tokyo",
          },
          {
            id: "VEN-TYO-009",
            name: "Meguro Cartridge Outlet",
            latitude: 35.6762,
            longitude: 139.6503,
            location: "Meguro-ku, Tokyo",
          },
          {
            id: "VEN-TYO-010",
            name: "Odaiba Digital Office Hub",
            latitude: 35.6762,
            longitude: 139.6503,
            location: "Koto-ku, Tokyo",
          },
        ],
      },
    ],
  },
  {
    country: "India",
    state: "India",
    latitude: 20.5937,
    longitude: 78.9629,
    hub: {
      city: "Mumbai",
      latitude: 19.076,
      longitude: 72.8777,
    },
    cities: [
      {
        city: "Mumbai",
        latitude: 19.076,
        longitude: 72.8777,
        suppliers: [
          {
            id: "SUP-MUM-001",
            name: "MAYUR COMPUTERS",
            latitude: 19.076,
            longitude: 72.8777,
            location: "Dadar East, Mumbai",
          },
          {
            id: "SUP-MUM-002",
            name: "Jet Cartridge (I) Private Limited",
            latitude: 19.076,
            longitude: 72.8777,
            location: "Dadar West, Mumbai",
          },
          {
            id: "SUP-MUM-003",
            name: "Hi-Tech",
            latitude: 19.076,
            longitude: 72.8777,
            location: "Dadar West, Mumbai",
          },
          {
            id: "SUP-MUM-004",
            name: "ABM Enterprises",
            latitude: 19.076,
            longitude: 72.8777,
            location: "Matunga, Mumbai",
          },
          {
            id: "SUP-MUM-005",
            name: "Ashapura Office Solutions",
            latitude: 19.076,
            longitude: 72.8777,
            location: "Fort, Mumbai",
          },
          {
            id: "SUP-MUM-006",
            name: "Cartridge World",
            latitude: 19.076,
            longitude: 72.8777,
            location: "Fort, Mumbai",
          },
          {
            id: "SUP-MUM-007",
            name: "SPT-Star Print Technology",
            latitude: 19.076,
            longitude: 72.8777,
            location: "Lower Parel, Mumbai",
          },
          {
            id: "SUP-MUM-008",
            name: "Cartridge King",
            latitude: 19.076,
            longitude: 72.8777,
            location: "Andheri East, Mumbai",
          },
          {
            id: "SUP-MUM-009",
            name: "Print Tonic Technologies",
            latitude: 19.076,
            longitude: 72.8777,
            location: "Bandra West, Mumbai",
          },
          {
            id: "SUP-MUM-010",
            name: "AquaPrint Enterprises",
            latitude: 19.076,
            longitude: 72.8777,
            location: "Kurla, Mumbai",
          },
        ],
        vendors: [
          {
            id: "VEN-MUM-001",
            name: "MAYUR COMPUTERS",
            latitude: 19.076,
            longitude: 72.8777,
            location: "Fort, Mumbai",
          },
          {
            id: "VEN-MUM-002",
            name: "LT Online Store",
            latitude: 19.076,
            longitude: 72.8777,
            location: "Dadar, Mumbai",
          },
          {
            id: "VEN-MUM-003",
            name: "Radha Enterprises",
            latitude: 19.076,
            longitude: 72.8777,
            location: "Matunga, Mumbai",
          },
          {
            id: "VEN-MUM-004",
            name: "Zigma Toner",
            latitude: 19.076,
            longitude: 72.8777,
            location: "Mahim, Mumbai",
          },
          {
            id: "VEN-MUM-005",
            name: "Cartridge Point",
            latitude: 19.076,
            longitude: 72.8777,
            location: "Wadala, Mumbai",
          },
          {
            id: "VEN-MUM-006",
            name: "Series Enterprises",
            latitude: 19.076,
            longitude: 72.8777,
            location: "BKC, Mumbai",
          },
          {
            id: "VEN-MUM-007",
            name: "We Tech Print Solution",
            latitude: 19.076,
            longitude: 72.8777,
            location: "Lower Parel, Mumbai",
          },
          {
            id: "VEN-MUM-008",
            name: "Computer Consumables Company",
            latitude: 19.076,
            longitude: 72.8777,
            location: "Girgaon, Mumbai",
          },
          {
            id: "VEN-MUM-009",
            name: "Navrang Enterprises",
            latitude: 19.076,
            longitude: 72.8777,
            location: "Nariman Point, Mumbai",
          },
          {
            id: "VEN-MUM-010",
            name: "Toner Cartridge Refilling",
            latitude: 19.076,
            longitude: 72.8777,
            location: "Vile Parle, Mumbai",
          },
        ],
      },
    ],
  },
  {
    country: "United Kingdom",
    state: "United Kingdom",
    latitude: 55.3781,
    longitude: -3.436,
    hub: {
      city: "London",
      latitude: 51.5074,
      longitude: -0.1278,
    },
    cities: [
      {
        city: "London",
        latitude: 51.5074,
        longitude: -0.1278,
        suppliers: [
          {
            id: "SUP-LDN-001",
            name: "London Central Cartridges Ltd",
            latitude: 51.5074,
            longitude: -0.1278,
            location: "City of London, London",
          },
          {
            id: "SUP-LDN-002",
            name: "Thames Print & Toner Supplies",
            latitude: 51.5074,
            longitude: -0.1278,
            location: "Southwark, London",
          },
          {
            id: "SUP-LDN-003",
            name: "Westminster Office Hub",
            latitude: 51.5074,
            longitude: -0.1278,
            location: "Westminster, London",
          },
          {
            id: "SUP-LDN-004",
            name: "Canary Wharf Corporate Supplies",
            latitude: 51.5074,
            longitude: -0.1278,
            location: "Docklands, London",
          },
          {
            id: "SUP-LDN-005",
            name: "Kings Cross Laser Depot",
            latitude: 51.5074,
            longitude: -0.1278,
            location: "Camden, London",
          },
          {
            id: "SUP-LDN-006",
            name: "Soho Cartridge & Ink Solutions",
            latitude: 51.5074,
            longitude: -0.1278,
            location: "Soho, London",
          },
          {
            id: "SUP-LDN-007",
            name: "Kensington Imaging Tech",
            latitude: 51.5074,
            longitude: -0.1278,
            location: "Kensington, London",
          },
          {
            id: "SUP-LDN-008",
            name: "Covent Garden Stationery Co.",
            latitude: 51.5074,
            longitude: -0.1278,
            location: "West End, London",
          },
          {
            id: "SUP-LDN-009",
            name: "Greenwich Print Consumables",
            latitude: 51.5074,
            longitude: -0.1278,
            location: "Greenwich, London",
          },
          {
            id: "SUP-LDN-010",
            name: "Holborn Legal Print Supply",
            latitude: 51.5074,
            longitude: -0.1278,
            location: "Holborn, London",
          },
        ],
        vendors: [
          {
            id: "VEN-LDN-001",
            name: "Fleet Street Print Mart",
            latitude: 51.5074,
            longitude: -0.1278,
            location: "City of London, London",
          },
          {
            id: "VEN-LDN-002",
            name: "Mayfair Corporate Stationers",
            latitude: 51.5074,
            longitude: -0.1278,
            location: "Mayfair, London",
          },
          {
            id: "VEN-LDN-003",
            name: "Piccadilly Toner Store",
            latitude: 51.5074,
            longitude: -0.1278,
            location: "Piccadilly, London",
          },
          {
            id: "VEN-LDN-004",
            name: "Victoria Station Office Shop",
            latitude: 51.5074,
            longitude: -0.1278,
            location: "Victoria, London",
          },
          {
            id: "VEN-LDN-005",
            name: "Paddington Express Cartridges",
            latitude: 51.5074,
            longitude: -0.1278,
            location: "Paddington, London",
          },
          {
            id: "VEN-LDN-006",
            name: "Shoreditch Creative Print Hub",
            latitude: 51.5074,
            longitude: -0.1278,
            location: "Shoreditch, London",
          },
          {
            id: "VEN-LDN-007",
            name: "Chelsea Fine Stationery",
            latitude: 51.5074,
            longitude: -0.1278,
            location: "Chelsea, London",
          },
          {
            id: "VEN-LDN-008",
            name: "Islington Business Supplies",
            latitude: 51.5074,
            longitude: -0.1278,
            location: "Islington, London",
          },
          {
            id: "VEN-LDN-009",
            name: "Clapham Commercial Print",
            latitude: 51.5074,
            longitude: -0.1278,
            location: "Clapham, London",
          },
          {
            id: "VEN-LDN-010",
            name: "Stratford Tech & Toner",
            latitude: 51.5074,
            longitude: -0.1278,
            location: "Stratford, London",
          },
        ],
      },
    ],
  },
  {
    country: "France",
    state: "France",
    latitude: 46.2276,
    longitude: 2.2137,
    hub: {
      city: "Paris",
      latitude: 48.8566,
      longitude: 2.3522,
    },
    cities: [
      {
        city: "Paris",
        latitude: 48.8566,
        longitude: 2.3522,
        suppliers: [
          {
            id: "SUP-PAR-001",
            name: "Paris Cartouche Distribution",
            latitude: 48.8566,
            longitude: 2.3522,
            location: "1er Arrondissement, Paris",
          },
          {
            id: "SUP-PAR-002",
            name: "Île-de-France Bureau & Toner",
            latitude: 48.8566,
            longitude: 2.3522,
            location: "La Défense, Paris",
          },
          {
            id: "SUP-PAR-003",
            name: "Seine Print Services SAS",
            latitude: 48.8566,
            longitude: 2.3522,
            location: "8ème Arrondissement, Paris",
          },
          {
            id: "SUP-PAR-004",
            name: "Montparnasse Laser Toner",
            latitude: 48.8566,
            longitude: 2.3522,
            location: "14ème Arrondissement, Paris",
          },
          {
            id: "SUP-PAR-005",
            name: "Bastille Bureau Solutions",
            latitude: 48.8566,
            longitude: 2.3522,
            location: "11ème Arrondissement, Paris",
          },
          {
            id: "SUP-PAR-006",
            name: "Champs-Élysées Corporate Supplies",
            latitude: 48.8566,
            longitude: 2.3522,
            location: "8ème Arrondissement, Paris",
          },
          {
            id: "SUP-PAR-007",
            name: "Le Marais Papeterie & Encre",
            latitude: 48.8566,
            longitude: 2.3522,
            location: "4ème Arrondissement, Paris",
          },
          {
            id: "SUP-PAR-008",
            name: "Opéra Imagerie Numérique",
            latitude: 48.8566,
            longitude: 2.3522,
            location: "9ème Arrondissement, Paris",
          },
          {
            id: "SUP-PAR-009",
            name: "Saint-Germain Cartouches",
            latitude: 48.8566,
            longitude: 2.3522,
            location: "6ème Arrondissement, Paris",
          },
          {
            id: "SUP-PAR-010",
            name: "Bercy Logistique Consommables",
            latitude: 48.8566,
            longitude: 2.3522,
            location: "12ème Arrondissement, Paris",
          },
        ],
        vendors: [
          {
            id: "VEN-PAR-001",
            name: "La Défense Print Mart",
            latitude: 48.8566,
            longitude: 2.3522,
            location: "Puteaux, Paris",
          },
          {
            id: "VEN-PAR-002",
            name: "Boulevard Haussmann Bureau",
            latitude: 48.8566,
            longitude: 2.3522,
            location: "9ème Arrondissement, Paris",
          },
          {
            id: "VEN-PAR-003",
            name: "République Toner Express",
            latitude: 48.8566,
            longitude: 2.3522,
            location: "3ème Arrondissement, Paris",
          },
          {
            id: "VEN-PAR-004",
            name: "Latin Quarter Stationery",
            latitude: 48.8566,
            longitude: 2.3522,
            location: "5ème Arrondissement, Paris",
          },
          {
            id: "VEN-PAR-005",
            name: "Nation Impression Direct",
            latitude: 48.8566,
            longitude: 2.3522,
            location: "12ème Arrondissement, Paris",
          },
          {
            id: "VEN-PAR-006",
            name: "Montmartre Fournitures",
            latitude: 48.8566,
            longitude: 2.3522,
            location: "18ème Arrondissement, Paris",
          },
          {
            id: "VEN-PAR-007",
            name: "Passy Laser Service",
            latitude: 48.8566,
            longitude: 2.3522,
            location: "16ème Arrondissement, Paris",
          },
          {
            id: "VEN-PAR-008",
            name: "Gare de Lyon Office Point",
            latitude: 48.8566,
            longitude: 2.3522,
            location: "12ème Arrondissement, Paris",
          },
          {
            id: "VEN-PAR-009",
            name: "Vaugirard Cartouche Boutique",
            latitude: 48.8566,
            longitude: 2.3522,
            location: "15ème Arrondissement, Paris",
          },
          {
            id: "VEN-PAR-010",
            name: "Étoile Consommables Store",
            latitude: 48.8566,
            longitude: 2.3522,
            location: "17ème Arrondissement, Paris",
          },
        ],
      },
    ],
  },
  {
    country: "South Korea",
    state: "South Korea",
    latitude: 35.9078,
    longitude: 127.7669,
    hub: {
      city: "Seoul",
      latitude: 37.5665,
      longitude: 126.978,
    },
    cities: [
      {
        city: "Seoul",
        latitude: 37.5665,
        longitude: 126.978,
        suppliers: [
          {
            id: "SUP-SEL-001",
            name: "Seoul Tech Supplies Corp",
            latitude: 37.5665,
            longitude: 126.978,
            location: "Gangnam-gu, Seoul",
          },
          {
            id: "SUP-SEL-002",
            name: "Han River Office Logistics",
            latitude: 37.5665,
            longitude: 126.978,
            location: "Yeongdeungpo-gu, Seoul",
          },
          {
            id: "SUP-SEL-003",
            name: "Jongno Laser Cartridge Center",
            latitude: 37.5665,
            longitude: 126.978,
            location: "Jongno-gu, Seoul",
          },
          {
            id: "SUP-SEL-004",
            name: "Teheran Valley Print Hub",
            latitude: 37.5665,
            longitude: 126.978,
            location: "Gangnam, Seoul",
          },
          {
            id: "SUP-SEL-005",
            name: "Guro Digital Complex Supplies",
            latitude: 37.5665,
            longitude: 126.978,
            location: "Guro-gu, Seoul",
          },
          {
            id: "SUP-SEL-006",
            name: "Mapo Imaging Innovations",
            latitude: 37.5665,
            longitude: 126.978,
            location: "Mapo-gu, Seoul",
          },
          {
            id: "SUP-SEL-007",
            name: "Dongdaemun Office Consumables",
            latitude: 37.5665,
            longitude: 126.978,
            location: "Dongdaemun-gu, Seoul",
          },
          {
            id: "SUP-SEL-008",
            name: "Songpa Corporate Toner",
            latitude: 37.5665,
            longitude: 126.978,
            location: "Songpa-gu, Seoul",
          },
          {
            id: "SUP-SEL-009",
            name: "Yongsan Electronics Print Depot",
            latitude: 37.5665,
            longitude: 126.978,
            location: "Yongsan-gu, Seoul",
          },
          {
            id: "SUP-SEL-010",
            name: "Seocho Laser Technologies",
            latitude: 37.5665,
            longitude: 126.978,
            location: "Seocho-gu, Seoul",
          },
        ],
        vendors: [
          {
            id: "VEN-SEL-001",
            name: "Gangnam Office Mart Direct",
            latitude: 37.5665,
            longitude: 126.978,
            location: "Gangnam Station, Seoul",
          },
          {
            id: "VEN-SEL-002",
            name: "Yeouido Financial Toner Shop",
            latitude: 37.5665,
            longitude: 126.978,
            location: "Yeouido, Seoul",
          },
          {
            id: "VEN-SEL-003",
            name: "Myeongdong Print Station",
            latitude: 37.5665,
            longitude: 126.978,
            location: "Jung-gu, Seoul",
          },
          {
            id: "VEN-SEL-004",
            name: "Hongdae Stationery & Print",
            latitude: 37.5665,
            longitude: 126.978,
            location: "Seogyo-dong, Seoul",
          },
          {
            id: "VEN-SEL-005",
            name: "COEX Business Solution Store",
            latitude: 37.5665,
            longitude: 126.978,
            location: "Samseong-dong, Seoul",
          },
          {
            id: "VEN-SEL-006",
            name: "Pangyo Tech Valley Hub",
            latitude: 37.5665,
            longitude: 126.978,
            location: "Bundang-gu, Seoul",
          },
          {
            id: "VEN-SEL-007",
            name: "Sinchon Digital Print Retail",
            latitude: 37.5665,
            longitude: 126.978,
            location: "Seodaemun-gu, Seoul",
          },
          {
            id: "VEN-SEL-008",
            name: "Itaewon Global Supply Mart",
            latitude: 37.5665,
            longitude: 126.978,
            location: "Yongsan, Seoul",
          },
          {
            id: "VEN-SEL-009",
            name: "Insa-dong Office Supplies",
            latitude: 37.5665,
            longitude: 126.978,
            location: "Jongno, Seoul",
          },
          {
            id: "VEN-SEL-010",
            name: "Jamsil Lotte Tower Office Store",
            latitude: 37.5665,
            longitude: 126.978,
            location: "Songpa, Seoul",
          },
        ],
      },
    ],
  },
  {
    country: "Netherlands",
    state: "Netherlands",
    latitude: 52.1326,
    longitude: 5.2913,
    hub: {
      city: "Rotterdam",
      latitude: 51.9244,
      longitude: 4.4777,
    },
    cities: [
      {
        city: "Rotterdam",
        latitude: 51.9244,
        longitude: 4.4777,
        suppliers: [
          {
            id: "SUP-RTM-001",
            name: "Rotterdam Port Toner Logistics",
            latitude: 51.9244,
            longitude: 4.4777,
            location: "Centrum, Rotterdam",
          },
          {
            id: "SUP-RTM-002",
            name: "Euro Toner Distribution BV",
            latitude: 51.9244,
            longitude: 4.4777,
            location: "Kop van Zuid, Rotterdam",
          },
          {
            id: "SUP-RTM-003",
            name: "Maas Laser & Print Supplies",
            latitude: 51.9244,
            longitude: 4.4777,
            location: "Feijenoord, Rotterdam",
          },
          {
            id: "SUP-RTM-004",
            name: "Holland Office Hub BV",
            latitude: 51.9244,
            longitude: 4.4777,
            location: "Delfshaven, Rotterdam",
          },
          {
            id: "SUP-RTM-005",
            name: "Europoort Cartridge Services",
            latitude: 51.9244,
            longitude: 4.4777,
            location: "Waalhaven, Rotterdam",
          },
          {
            id: "SUP-RTM-006",
            name: "Erasmus Business Supplies",
            latitude: 51.9244,
            longitude: 4.4777,
            location: "Kralingen, Rotterdam",
          },
          {
            id: "SUP-RTM-007",
            name: "Delta Print Consumables",
            latitude: 51.9244,
            longitude: 4.4777,
            location: "Noord, Rotterdam",
          },
          {
            id: "SUP-RTM-008",
            name: "Rotterdam Maritime Stationery",
            latitude: 51.9244,
            longitude: 4.4777,
            location: "Charlois, Rotterdam",
          },
          {
            id: "SUP-RTM-009",
            name: "Schie Toner Technologies",
            latitude: 51.9244,
            longitude: 4.4777,
            location: "Overschie, Rotterdam",
          },
          {
            id: "SUP-RTM-010",
            name: "Benelux Imaging Solutions",
            latitude: 51.9244,
            longitude: 4.4777,
            location: "Hillegersberg, Rotterdam",
          },
        ],
        vendors: [
          {
            id: "VEN-RTM-001",
            name: "Rotterdam Centraal Print Shop",
            latitude: 51.9244,
            longitude: 4.4777,
            location: "Stationsplein, Rotterdam",
          },
          {
            id: "VEN-RTM-002",
            name: "Coolsingel Office Depot",
            latitude: 51.9244,
            longitude: 4.4777,
            location: "Coolsingel, Rotterdam",
          },
          {
            id: "VEN-RTM-003",
            name: "Erasmusbrug Toner Mart",
            latitude: 51.9244,
            longitude: 4.4777,
            location: "Willemskade, Rotterdam",
          },
          {
            id: "VEN-RTM-004",
            name: "Markthal Stationery Corner",
            latitude: 51.9244,
            longitude: 4.4777,
            location: "Binnenrotte, Rotterdam",
          },
          {
            id: "VEN-RTM-005",
            name: "Zuidplein Commercial Supplies",
            latitude: 51.9244,
            longitude: 4.4777,
            location: "Zuidplein, Rotterdam",
          },
          {
            id: "VEN-RTM-006",
            name: "Delfshaven Laser Point",
            latitude: 51.9244,
            longitude: 4.4777,
            location: "Haven, Rotterdam",
          },
          {
            id: "VEN-RTM-007",
            name: "Euromast Business Services",
            latitude: 51.9244,
            longitude: 4.4777,
            location: "Parkhaven, Rotterdam",
          },
          {
            id: "VEN-RTM-008",
            name: "Blaak Print Retail",
            latitude: 51.9244,
            longitude: 4.4777,
            location: "Blaak, Rotterdam",
          },
          {
            id: "VEN-RTM-009",
            name: "West-Kruiskade Office Mart",
            latitude: 51.9244,
            longitude: 4.4777,
            location: "Oude Westen, Rotterdam",
          },
          {
            id: "VEN-RTM-010",
            name: "Maashaven Industrial Store",
            latitude: 51.9244,
            longitude: 4.4777,
            location: "Afrikaanderwijk, Rotterdam",
          },
        ],
      },
    ],
  },
  {
    country: "Singapore",
    state: "Singapore",
    latitude: 1.3521,
    longitude: 103.8198,
    hub: {
      city: "Singapore",
      latitude: 1.3521,
      longitude: 103.8198,
    },
    cities: [
      {
        city: "Singapore",
        latitude: 1.3521,
        longitude: 103.8198,
        suppliers: [
          {
            id: "SUP-SIN-001",
            name: "Lion City Toner Logistics",
            latitude: 1.3521,
            longitude: 103.8198,
            location: "Raffles Place, Singapore",
          },
          {
            id: "SUP-SIN-002",
            name: "Marina Bay Office Supplies Pte Ltd",
            latitude: 1.3521,
            longitude: 103.8198,
            location: "Marina Bay, Singapore",
          },
          {
            id: "SUP-SIN-003",
            name: "Jurong Print & Cartridge Hub",
            latitude: 1.3521,
            longitude: 103.8198,
            location: "Jurong East, Singapore",
          },
          {
            id: "SUP-SIN-004",
            name: "Changi Logistics Consumables",
            latitude: 1.3521,
            longitude: 103.8198,
            location: "Changi South, Singapore",
          },
          {
            id: "SUP-SIN-005",
            name: "Orchard Corporate Stationery",
            latitude: 1.3521,
            longitude: 103.8198,
            location: "Orchard Road, Singapore",
          },
          {
            id: "SUP-SIN-006",
            name: "Tanjong Pagar Imaging Co.",
            latitude: 1.3521,
            longitude: 103.8198,
            location: "Tanjong Pagar, Singapore",
          },
          {
            id: "SUP-SIN-007",
            name: "Woodlands Industrial Toner",
            latitude: 1.3521,
            longitude: 103.8198,
            location: "Woodlands, Singapore",
          },
          {
            id: "SUP-SIN-008",
            name: "Suntec City Office Solutions",
            latitude: 1.3521,
            longitude: 103.8198,
            location: "Marina Centre, Singapore",
          },
          {
            id: "SUP-SIN-009",
            name: "Bugis Laser Print Supplies",
            latitude: 1.3521,
            longitude: 103.8198,
            location: "Bugis, Singapore",
          },
          {
            id: "SUP-SIN-010",
            name: "One-North Tech Consumables",
            latitude: 1.3521,
            longitude: 103.8198,
            location: "Buona Vista, Singapore",
          },
        ],
        vendors: [
          {
            id: "VEN-SIN-001",
            name: "Raffles Business Mart",
            latitude: 1.3521,
            longitude: 103.8198,
            location: "Battery Road, Singapore",
          },
          {
            id: "VEN-SIN-002",
            name: "Marina Financial Print Services",
            latitude: 1.3521,
            longitude: 103.8198,
            location: "Marina Boulevard, Singapore",
          },
          {
            id: "VEN-SIN-003",
            name: "Shenton Way Toner Store",
            latitude: 1.3521,
            longitude: 103.8198,
            location: "Shenton Way, Singapore",
          },
          {
            id: "VEN-SIN-004",
            name: "City Hall Stationery Depot",
            latitude: 1.3521,
            longitude: 103.8198,
            location: "North Bridge Road, Singapore",
          },
          {
            id: "VEN-SIN-005",
            name: "Somerset Print Solutions",
            latitude: 1.3521,
            longitude: 103.8198,
            location: "Orchard Road, Singapore",
          },
          {
            id: "VEN-SIN-006",
            name: "HarbourFront Office Mart",
            latitude: 1.3521,
            longitude: 103.8198,
            location: "Telok Blangah, Singapore",
          },
          {
            id: "VEN-SIN-007",
            name: "Tampines Regional Supply Hub",
            latitude: 1.3521,
            longitude: 103.8198,
            location: "Tampines Central, Singapore",
          },
          {
            id: "VEN-SIN-008",
            name: "Novena Commercial Supplies",
            latitude: 1.3521,
            longitude: 103.8198,
            location: "Thomson Road, Singapore",
          },
          {
            id: "VEN-SIN-009",
            name: "Paya Lebar Square Print Mart",
            latitude: 1.3521,
            longitude: 103.8198,
            location: "Paya Lebar, Singapore",
          },
          {
            id: "VEN-SIN-010",
            name: "Clarke Quay Corporate Services",
            latitude: 1.3521,
            longitude: 103.8198,
            location: "Merchant Road, Singapore",
          },
        ],
      },
    ],
  },
];

// Calculate distance in kilometers
export const calculateDistance = (lat1, lon1, lat2, lon2) => {
  const R = 6371;
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLon = ((lon2 - lon1) * Math.PI) / 180;
  const a =
    Math.sin(dLat / 2) ** 2 +
    Math.cos((lat1 * Math.PI) / 180) *
      Math.cos((lat2 * Math.PI) / 180) *
      Math.sin(dLon / 2) ** 2;
  return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
};

// Disperse identical coordinates radially so pins are visually distinct on map
export const getEffectiveCoordinates = (
  item,
  index,
  total,
  centerLat,
  centerLng
) => {
  if (
    item.lat &&
    item.lng &&
    (Math.abs(item.lat - centerLat) > 0.002 ||
      Math.abs(item.lng - centerLng) > 0.002)
  ) {
    return { lat: item.lat, lng: item.lng };
  }
  const angle = (index / Math.max(total, 1)) * 2 * Math.PI - Math.PI / 2;
  const radius = 0.016 + (index % 3) * 0.008;
  return {
    lat: Number((centerLat + Math.sin(angle) * radius).toFixed(5)),
    lng: Number((centerLng + Math.cos(angle) * (radius * 1.05)).toFixed(5)),
  };
};
