import { MarkerType } from '@xyflow/react';

export const nodeCategories = [
  {
    category: '1. Basic Nodes',
    items: [
      {
        id: 'palette-start',
        name: 'Start / End',
        description: 'Define the start or end of your flow',
        icon: 'Rocket',
        color: '#22c55e',
        bg: '#f0fdf4',
        border: '#86efac',
        type: 'startEndNode',
      },
      {
        id: 'palette-action',
        name: 'Action',
        description: 'Perform an action (e.g. send email, update data)',
        icon: 'Settings',
        color: '#3b82f6',
        bg: '#eff6ff',
        border: '#93c5fd',
        type: 'actionNode',
      },
      {
        id: 'palette-user-input',
        name: 'User Input',
        description: 'Get input from user (e.g. form, select, text)',
        icon: 'Users',
        color: '#a855f7',
        bg: '#faf5ff',
        border: '#d8b4fe',
        type: 'inputNode',
      },
      {
        id: 'palette-message',
        name: 'Message',
        description: 'Send message (email, SMS, WhatsApp, notification)',
        icon: 'Mail',
        color: '#0d9488',
        bg: '#f0fdfa',
        border: '#99f6e4',
        type: 'messageNode',
      },
    ],
  },
  {
    category: '2. Logic & Control',
    items: [
      {
        id: 'palette-condition',
        name: 'Condition',
        description: 'Add if/else conditions',
        icon: 'Sparkles',
        color: '#f97316',
        bg: '#fff7ed',
        border: '#fdba74',
        type: 'conditionNode',
      },
      {
        id: 'palette-switch',
        name: 'Switch',
        description: 'Route based on multiple conditions',
        icon: 'Trending',
        color: '#ec4899',
        bg: '#fdf2f8',
        border: '#fbcfe8',
        type: 'switchNode',
      },
      {
        id: 'palette-loop',
        name: 'Loop',
        description: 'Repeat a process',
        icon: 'Refresh',
        color: '#8b5cf6',
        bg: '#f5f3ff',
        border: '#ddd6fe',
        type: 'loopNode',
      },
    ],
  },
  {
    category: '3. Data & Integration',
    items: [
      {
        id: 'palette-api',
        name: 'API',
        description: 'Call external API',
        icon: 'Code',
        color: '#06b6d4',
        bg: '#ecfeff',
        border: '#a5f3fc',
        type: 'apiNode',
      },
      {
        id: 'palette-database',
        name: 'Database',
        description: 'Read / Write data',
        icon: 'Layers',
        color: '#2563eb',
        bg: '#eff6ff',
        border: '#93c5fd',
        type: 'databaseNode',
      },
    ],
  },
  {
    category: '4. Other',
    items: [
      {
        id: 'palette-note',
        name: 'Note',
        description: 'Add notes / comments',
        icon: 'File',
        color: '#eab308',
        bg: '#fefce8',
        border: '#fde047',
        type: 'noteNode',
      },
      {
        id: 'palette-delay',
        name: 'Delay',
        description: 'Wait for a specific time',
        icon: 'Clock',
        color: '#64748b',
        bg: '#f8fafc',
        border: '#cbd5e1',
        type: 'delayNode',
      },
    ],
  },
];

export const initialNodes = [
  {
    id: '1',
    type: 'startEndNode',
    position: { x: 260, y: 20 },
    data: {
      title: 'Start',
      subtitle: 'B2B Customer Journey',
      nodeType: 'Start / End',
      color: '#22c55e',
      bg: '#f0fdf4',
      border: '#86efac',
      icon: 'Rocket',
      hasTopHandle: false,
      hasBottomHandle: true,
    },
  },
  {
    id: '2',
    type: 'inputNode',
    position: { x: 260, y: 115 },
    data: {
      title: 'Select Seller Type',
      subtitle: 'Manufacturer, Trader, Stockiest, Vendor, Wholeseller, etc.',
      nodeType: 'User Input',
      color: '#a855f7',
      bg: '#faf5ff',
      border: '#d8b4fe',
      icon: 'Users',
      hasTopHandle: true,
      hasBottomHandle: true,
    },
  },
  {
    id: '3',
    type: 'actionNode',
    position: { x: 260, y: 210 },
    data: {
      title: 'Explore Products / Services',
      subtitle: 'View catalog, search, filter, check details',
      nodeType: 'Action',
      color: '#3b82f6',
      bg: '#eff6ff',
      border: '#93c5fd',
      icon: 'Search',
      hasTopHandle: true,
      hasBottomHandle: true,
    },
  },
  {
    id: '4',
    type: 'conditionNode',
    position: { x: 285, y: 310 },
    data: {
      title: 'Interested?',
      subtitle: 'Check if customer shows interest',
      nodeType: 'Condition',
      color: '#f97316',
      bg: '#fff7ed',
      border: '#fdba74',
      icon: 'Sparkles',
      conditionType: 'If / Else',
      conditionLogic: 'Customer response',
      conditionOperator: 'Equals',
      conditionValue: 'Interested',
      otherwise: 'Otherwise',
      posX: 520,
      posY: 240,
      hasTopHandle: true,
      hasBottomHandle: false,
    },
  },
  {
    id: '5',
    type: 'messageNode',
    position: { x: 20, y: 400 },
    data: {
      title: 'Send Follow-up',
      subtitle: 'Share more info, offers, case studies',
      nodeType: 'Message',
      color: '#f43f5e',
      bg: '#fff1f2',
      border: '#fecdd3',
      icon: 'Mail',
      hasTopHandle: true,
      hasBottomHandle: true,
    },
  },
  {
    id: '6',
    type: 'delayNode',
    position: { x: 20, y: 495 },
    data: {
      title: 'Wait',
      subtitle: '3–5 days',
      nodeType: 'Delay',
      color: '#64748b',
      bg: '#f8fafc',
      border: '#cbd5e1',
      icon: 'Clock',
      hasTopHandle: true,
      hasBottomHandle: true,
    },
  },
  {
    id: '7',
    type: 'inputNode',
    position: { x: 20, y: 590 },
    data: {
      title: 'Re-engage',
      subtitle: 'Email / WhatsApp / Call',
      nodeType: 'User Input',
      color: '#8b5cf6',
      bg: '#f5f3ff',
      border: '#ddd6fe',
      icon: 'Users',
      hasTopHandle: true,
      hasBottomHandle: true,
    },
  },
  {
    id: '8',
    type: 'actionNode',
    position: { x: 500, y: 360 },
    data: {
      title: 'Submit Enquiry / Request Demo',
      subtitle: 'Fill form or book a demo',
      nodeType: 'Action',
      color: '#0d9488',
      bg: '#f0fdfa',
      border: '#99f6e4',
      icon: 'File',
      hasTopHandle: true,
      hasBottomHandle: true,
    },
  },
  {
    id: '9',
    type: 'actionNode',
    position: { x: 500, y: 445 },
    data: {
      title: 'Send to Manufacturer',
      subtitle: 'Share requirements with manufacturer',
      nodeType: 'Action',
      color: '#10b981',
      bg: '#ecfdf5',
      border: '#a7f3d0',
      icon: 'Analytic',
      hasTopHandle: true,
      hasBottomHandle: true,
    },
  },
  {
    id: '10',
    type: 'actionNode',
    position: { x: 500, y: 530 },
    data: {
      title: 'Product Quotation & Negotiation',
      subtitle: 'Discuss price, MOQ, timeline',
      nodeType: 'Action',
      color: '#a855f7',
      bg: '#faf5ff',
      border: '#d8b4fe',
      icon: 'Receipt',
      hasTopHandle: true,
      hasBottomHandle: true,
    },
  },
  {
    id: '11',
    type: 'actionNode',
    position: { x: 500, y: 615 },
    data: {
      title: 'Place Order',
      subtitle: 'Confirm order & payment',
      nodeType: 'Action',
      color: '#3b82f6',
      bg: '#eff6ff',
      border: '#93c5fd',
      icon: 'Cart',
      hasTopHandle: true,
      hasBottomHandle: true,
    },
  },
  {
    id: '12',
    type: 'actionNode',
    position: { x: 500, y: 700 },
    data: {
      title: 'Delivery & Support',
      subtitle: 'Track order & after-sales support',
      nodeType: 'Action',
      color: '#6366f1',
      bg: '#eef2ff',
      border: '#c7d2fe',
      icon: 'Support',
      hasTopHandle: true,
      hasBottomHandle: true,
    },
  },
  {
    id: '13',
    type: 'startEndNode',
    position: { x: 250, y: 780 },
    data: {
      title: 'Customer Satisfied',
      subtitle: 'Long-term relationship & repeat orders',
      nodeType: 'Start / End',
      color: '#16a34a',
      bg: '#f0fdf4',
      border: '#86efac',
      icon: 'Check',
      hasTopHandle: true,
      hasLeftHandle: true,
      hasRightHandle: true,
      hasBottomHandle: false,
    },
  },
];

const defaultEdgeStyle = {
  stroke: '#64748b',
  strokeWidth: 1.5,
};

const defaultMarker = {
  type: MarkerType.ArrowClosed,
  width: 14,
  height: 14,
  color: '#64748b',
};

export const initialEdges = [
  {
    id: 'e1-2',
    source: '1',
    target: '2',
    type: 'smoothstep',
    style: defaultEdgeStyle,
    markerEnd: defaultMarker,
  },
  {
    id: 'e2-3',
    source: '2',
    target: '3',
    type: 'smoothstep',
    style: defaultEdgeStyle,
    markerEnd: defaultMarker,
  },
  {
    id: 'e3-4',
    source: '3',
    target: '4',
    type: 'smoothstep',
    style: defaultEdgeStyle,
    markerEnd: defaultMarker,
  },
  {
    id: 'e4-5',
    source: '4',
    sourceHandle: 'left',
    target: '5',
    type: 'smoothstep',
    style: { stroke: '#3b82f6', strokeWidth: 1.5 },
    markerEnd: { ...defaultMarker, color: '#3b82f6' },
    label: 'No',
    labelStyle: { fill: '#ef4444', fontWeight: 600, fontSize: 11 },
    labelBgPadding: [6, 2],
    labelBgBorderRadius: 10,
    labelBgStyle: { fill: '#fee2e2', stroke: '#fca5a5', strokeWidth: 1 },
  },
  {
    id: 'e4-8',
    source: '4',
    sourceHandle: 'right',
    target: '8',
    type: 'smoothstep',
    style: { stroke: '#3b82f6', strokeWidth: 1.5 },
    markerEnd: { ...defaultMarker, color: '#3b82f6' },
    label: 'Yes',
    labelStyle: { fill: '#16a34a', fontWeight: 600, fontSize: 11 },
    labelBgPadding: [6, 2],
    labelBgBorderRadius: 10,
    labelBgStyle: { fill: '#dcfce7', stroke: '#86efac', strokeWidth: 1 },
  },
  {
    id: 'e5-6',
    source: '5',
    target: '6',
    type: 'smoothstep',
    style: defaultEdgeStyle,
    markerEnd: defaultMarker,
  },
  {
    id: 'e6-7',
    source: '6',
    target: '7',
    type: 'smoothstep',
    style: defaultEdgeStyle,
    markerEnd: defaultMarker,
  },
  {
    id: 'e7-13',
    source: '7',
    target: '13',
    targetHandle: 'left',
    type: 'smoothstep',
    style: { stroke: '#3b82f6', strokeWidth: 1.5 },
    markerEnd: { ...defaultMarker, color: '#3b82f6' },
  },
  {
    id: 'e8-9',
    source: '8',
    target: '9',
    type: 'smoothstep',
    style: defaultEdgeStyle,
    markerEnd: defaultMarker,
  },
  {
    id: 'e9-10',
    source: '9',
    target: '10',
    type: 'smoothstep',
    style: defaultEdgeStyle,
    markerEnd: defaultMarker,
  },
  {
    id: 'e10-11',
    source: '10',
    target: '11',
    type: 'smoothstep',
    style: defaultEdgeStyle,
    markerEnd: defaultMarker,
  },
  {
    id: 'e11-12',
    source: '11',
    target: '12',
    type: 'smoothstep',
    style: defaultEdgeStyle,
    markerEnd: defaultMarker,
  },
  {
    id: 'e12-13',
    source: '12',
    target: '13',
    targetHandle: 'right',
    type: 'smoothstep',
    style: { stroke: '#3b82f6', strokeWidth: 1.5 },
    markerEnd: { ...defaultMarker, color: '#3b82f6' },
  },
];
